### ISSUE TITLE
Design guidelines

### ISSUE THREAD

**Issue by SteelAlloy** [contributor-assistant/contributor-assistant#23]
# Deno

- Use the latest standard modules as much as possible
- Avoid using `--unstable` APIs
- Save common dependencies (like octokit) in a single file
- Follow [Deno Style Guide](https://deno.land/manual/contributing/style_guide) when possible 

# Github Actions

Each Action is defined in its own folder in `/src`.
There are 3 ways to use a Contributor Assistant feature :

*Note: the code is actually the same for these 3 approaches.*

### 1. Action
This is the easiest and most natural way for a user to use a feature

```yaml
jobs:
  Contributor-Assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "Some feature"
        uses: cla-assistant/contributor-assistant/src/some-feature@v1.0.0
        with:
           option_1: value_1
           option_2: value_2
```

### 2. Running a Deno script

It's actually the same version as the one above, but without the github action abstraction.

```yaml
jobs:
  Contributor-Assistant:
    runs-on: ubuntu-latest
    steps:  
      - name: "Some feature"
        uses: denolib/setup-deno@v2
        with:
         deno-version: v1.x
      - run: deno run --allow-net https://raw.githubusercontent.com/cla-assistant/contributor-assistant/main/src/some-feature/cli.ts ${{ value_1 }} --option_2 ${{ value_2 }} 
```

### 3. API

In the event that the user needs to use the feature programmatically, he/she can import the functions and have greater control over the flow of events.

```ts
import { some_feature } from 'https://raw.githubusercontent.com/cla-assistant/contributor-assistant/main/src/some-feature/mod.ts'

some_feature({
  option_1: "value_1",
  option_2: "value_2",
});
```
